{
 "title": "Metrics Demo",
 "description": "General application specific demo metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } }
  ]
 },
 "panels": [
  {
   "title": "Tax Computations per Seconds",
   "type": "graph",
   "description": "Number of tax computation calls",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops", "label": "Tax Computations/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(metrics_demo_tax_computer_count_operations_total{application=\"$application\"}[5m]))"
    }
   ]
  },
  {
   "title": "Tax Computation Cache Utilization (percent)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_demo_tax_computer_cache_cache_utilization_percent",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Tax Computation Cache Hit Rate (percent)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*((metrics_demo_tax_computer_count_operations_total - metrics_demo_tax_computer_cache_miss_count_operations_total) /\n      metrics_demo_tax_computer_count_operations_total)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Tax Computation Request Duration Percentiles",
   "type": "graph",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "1000 * histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", method=\"GET\", uri=\"/computeTaxRate\"}[5m])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "1000 * histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", method=\"GET\", uri=\"/computeTaxRate\"}[5m])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "1000 * histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", method=\"GET\", uri=\"/computeTaxRate\"}[5m])) by (le))",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "Taxable Income",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 10 },
   "targets": [
    {
     "expr": "sum(increase(metrics_demo_taxable_income_ten_thousands_total[5m])) by (ten_thousands)",
     "legendFormat": "{{ten_thousands}}"
    }
   ]
  }
 ]
}