#-------------------------------------------------------------------------------
# default settings
# these settings are used, if not overridden by activating other profiles
#-------------------------------------------------------------------------------

server:
  port:              8100

spring:
  application:
    name:            "metrics-demo"
  cloud:
    consul:
      config:
        import-check:
          enabled:   false
      discovery:
        instanceId:  ${spring.application.name}:${random.value}

management:
  metrics:
    export:
      prometheus:
        enabled:         true
        descriptions:    true           # set this to "false" to remove descriptions from output
    tags:
      environment:       "development"  # common tag for all metrics
      application:       "${spring.application.name}"
    web:
      server:
        request:
          autotime:
            enabled:     true           # enables the instrumentation of requests handled by Spring MVC
            percentiles-histogram: false
    distribution:
      percentiles-histogram:
        all:             true           # enables percentiles histograms for all endpoints
  endpoints:
    web:
      exposure:
        include:         metrics, prometheus, health
  endpoint:
    health:
      show-details:      when_authorized       # one of "always"/"never"/"when-authorized"

logging:
  level:                     # specification of log levels
    ROOT:            WARN    # default log level

metrics-demo:
  tax-computer:
    cache:
      max-size:     100

#-------------------------------------------------------------------------------
# development Profile
# this profile should be used for local development
#-------------------------------------------------------------------------------
---
spring:
  config:
    activate:
      on-profile:    development
  cloud:
    consul:
      discovery:
        tags:
          - development
          - urlprefix-/
          - urlprefix-/css
          - urlprefix-/js
logging:
  level:                     # specification of log levels
    ROOT:            INFO    # default log level
    de.smartsteuer:  DEBUG   # default log level for smartsteuer classes

#-------------------------------------------------------------------------------
# production settings
# these settings are used to override default settings during production
#-------------------------------------------------------------------------------
---
spring:
  config:
    activate:
      on-profile: production
  cloud:
    consul:
      discovery:
        tags:
          - production
          - urlprefix-/
          - urlprefix-/css
          - urlprefix-/js

management:
  metrics:
    export:
      prometheus:
        descriptions:    false          # remove descriptions from output
    tags:
      environment:       "production"   # common tag for all metrics
